name: eanalytics
description: Eulerian Technologies - EAnalytics Flutter SDK. This SDK provides functionnalities for our augmented analytics platform. Get a free account at https://eulerian.io/
version: 1.1.0
homepage: https://github.com/EulerianTechnologies/eanalytics-flutter

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  advertising_id: ^2.0.0
  android_id: ^0.3.5
  async: ^2.5.0
  device_info_plus: ^9.0.3
  flutter:
    sdk: flutter
  http: ^1.1.0
  logger: ^2.0.2
  package_info_plus: ^4.1.0
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        default_package: eanalytics
      ios:
        default_package: eanalytics
      web:
        default_package: eanalytics
