name: eanalytics
description: Eulerian Technologies - EAnalytics Flutter SDK. This SDK provides functionnalities for our augmented analytics platform. Get a free account at https://eulerian.io/
version: 1.1.1
homepage: https://github.com/EulerianTechnologies/eanalytics-flutter

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  advertising_id: ^2.6.0
  android_id: ^0.4.0
  android_play_install_referrer: ^0.4.0
  async: ^2.11.0
  device_info_plus: ^11.5.0
  flutter:
    sdk: flutter
  http: ^1.2.1
  logger: ^2.2.0
  package_info_plus: ^8.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

